<a href="https://colab.research.google.com/github/HariomPrajapati09/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***NumPy - Numerical Python***

Advantages of NumPy Arrays:
  1. Allows several Mathematical Operations.
  2. Faster operations


In [ ]:
import numpy as np

***List v/s Numpy - time taken***

In [ ]:
from time import process_time

**Time taken by a list**

In [ ]:
py_list=[ 1 for i in range(10000)]
start_time=process_time()
py_list=[i*5 for i in py_list]
end_time=process_time()
print(end_time-start_time)

0.0009671630000003262


**Time taken by a Numpy**

In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array +=5
end_time=process_time()
print(end_time-start_time)

0.0001567879999999633


***Numpy Arrays***

In [ ]:
#List
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
#Numpy
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#Creating a 1D array
a=np.array([1,2,3,4,5])
print(a)
a.shape #Output represent the no. of columns

[1 2 3 4 5]


(5,)

In [ ]:
#Creating a 2D array
b=np.array([(1,2,3),(1,3,5)])
print(b)
b.shape #Output represent the no. of rows and columns

[[1 2 3]
 [1 3 5]]


(2, 3)

In [ ]:
c=np.array([(1,2,3),(1,3,5)],dtype=float) #dtype represent the data types
print(c)

[[1. 2. 3.]
 [1. 3. 5.]]


***Initial place holder in NumPy arrays***

In [ ]:
x=np.zeros((4,5)) #For all values Zeros
print("FOR ALL VALUES ZEROS")
print(x)

FOR ALL VALUES ZEROS
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y=np.ones((3,3)) #For all values Ones
print("FOR ALL VALUES ONES")
print(y)

FOR ALL VALUES ONES
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z=np.full((2,3),4) #For all values according to us
print("FOR ALL VALUES ACCORDING TO US")
print(z)


FOR ALL VALUES ACCORDING TO US
[[4 4 4]
 [4 4 4]]


In [ ]:
a=np.eye(4) #For identity matrix
print("FOR IDENTITY MATRIX")
print(a)

FOR IDENTITY MATRIX
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Creating a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.11908902 0.52566311 0.19604515 0.24086881]
 [0.86736606 0.96929734 0.23966379 0.40801349]
 [0.17716704 0.8638865  0.68785301 0.35100144]]


In [ ]:
#Creating a numpy array with random values in specific range
c=np.random.randint(10,100,(3,4))
print(c)

[[11 11 68 18]
 [91 17 69 16]
 [15 51 57 30]]


In [ ]:
#Creating a numpy array for evenly spaced value
#Specifying the number of values required
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#Creating a numpy array for evenly spaced value
#Specifying the step
e=np.arange(10,40,5)
print(e)

[10 15 20 25 30 35]


In [ ]:
#Converting a List into an numpy array
list2=[12,13,23,14]
np_arr=np.asarray(list2)
print(np_arr)
type(np_arr)

[12 13 23 14]


numpy.ndarray

***Analysing a numpy array***

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[32 34 25 37 49]
 [72 82 57 23 24]
 [37 85 31 73 72]
 [37 21 64 32 69]
 [86 57 20 19 28]]


In [ ]:
#Check no. of rows and columns
print(c.shape)

(5, 5)


In [ ]:
#Check the dimention of array
print(c.ndim)

2


In [ ]:
#Checking the no. of elements in array
print(c.size)

25


In [ ]:
#Checking the datatype of array
print(c.dtype)

int64


***Mathematical Operation on a numpy array***

In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[5 0 2]
 [3 0 2]
 [2 8 0]]
[[16 18 10]
 [17 11 13]
 [13 17 12]]


In [ ]:
print(a+b)

[[21 18 12]
 [20 11 15]
 [15 25 12]]


In [ ]:
print(a*b)

[[ 80   0  20]
 [ 51   0  26]
 [ 26 136   0]]


In [ ]:
print(a-b)

[[-11 -18  -8]
 [-14 -11 -11]
 [-11  -9 -12]]


In [ ]:
print(a/b)

[[0.3125     0.         0.2       ]
 [0.17647059 0.         0.15384615]
 [0.15384615 0.47058824 0.        ]]


In [ ]:
#Another way to perform add sub mult and div
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 18 12]
 [20 11 15]
 [15 25 12]]
[[-11 -18  -8]
 [-14 -11 -11]
 [-11  -9 -12]]
[[ 80   0  20]
 [ 51   0  26]
 [ 26 136   0]]
[[0.3125     0.         0.2       ]
 [0.17647059 0.         0.15384615]
 [0.15384615 0.47058824 0.        ]]


***Array Manipulation***

In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 5 9]
 [9 4 1]]
(2, 3)


In [ ]:
#Transpose of matrix
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[5 9]
 [5 4]
 [9 1]]
(3, 2)


In [ ]:
#Another way to transpose of matrix
trans1=array.T
print(trans1)

[[5 9]
 [5 4]
 [9 1]]


In [ ]:
#REshape of array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)
print()
b=a.reshape(3,2)
print(b)
print(b.shape)

[[9 3 0]
 [0 2 5]]
(2, 3)

[[9 3]
 [0 0]
 [2 5]]
(3, 2)
